# Generated by Django 3.2.16 on 2022-12-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'Personal info', 'verbose_name_plural': 'Personal info'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='domaine',
            field=models.URLField(verbose_name='Domain'),
        ),
    ]
