# Generated by Django 3.2.16 on 2022-12-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_userinfo_company_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='whatsapp',
            field=models.CharField(default=222, max_length=200, verbose_name='WhatsApp'),
            preserve_default=False,
        ),
    ]
