# Generated by Django 3.2.16 on 2022-12-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_userinfo_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Company or project Name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company_vat',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company VAT'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='domaine',
            field=models.URLField(blank=True, null=True, verbose_name='Domain'),
        ),
    ]
